<?php
// Check for valid url
if(!defined('ABSPATH')) {
	die("Better luck next time!!!");
}

global $wp_notify;
?>
<!-- ==== Generated by WP-Notify Plugin ==== -->
<style type="text/css">
<?php if($wp_notify[style] == "stackoverflow") : ?>
#notification {
	font-family:Arial,Helvetica,sans-serif;
	position:fixed;
	top:0;
	left:0;
	width:99%;
	z-index:105;
	text-align:left;
	font-weight:normal;
	font-size:100%;
	color:#<?= $wp_notify[text_color]?>;
	background-color:#<?= $wp_notify[bg_color]?>;
	padding:5px;
	border:1px solid #<?= $wp_notify[border_color]?>;
	display:none;
}

<?php elseif ($wp_notify[style] == "safariAlert"): ?>
#notification {
	background-color:#<?= $wp_notify[bg_color]?>;
	margin-top:-10px;
	padding-top:10px;
	width:500px;
	border:1px solid #<?= $wp_notify[border_color]?>;
	color:#<?= $wp_notify[text_color]?>;
	font-family:Arial,Helvetica,sans-serif;
	-moz-border-radius:10px;
	-webkit-border-radius:10px;
	border-radius:10px;
}
<?php elseif ($wp_notify[style] == "facebook"): ?>

#notification { 
	display:inline; 
	position:fixed; 
	bottom:5px; 
	margin-left:5px;
	font-weight:normal; 
	text-decoration:none; 
	border:1px solid #<?= $wp_notify[border_color]?>;
	color:#<?= $wp_notify[text_color]?>;
	background-color:#<?= $wp_notify[bg_color]?>;
	font-family:Arial,Helvetica,sans-serif;
	-moz-border-radius:5px;
	-webkit-border-radius:5px;
	border-radius:5px;
	display:none;
}
<?php endif; ?>
#notification *{color:#<?= $wp_notify[text_color]?>;}
#notification span#notify_message{float:left;width:92%;padding:5px;}
#notification span.dismiss {cursor:pointer;float:right;background-color:#<?= $wp_notify[button_bg_color]?>;}
#notification ul{padding:0;margin:0}
#notification .notify_posts{padding:0;list-style:none;}
#notification span.dismiss a {color:#<?= $wp_notify[button_text_color]?>;border:1px solid #<?= $wp_notify[button_border_color]?>;text-decoration:none;font-weight:bold;padding:1px 5px;}
</style>
<!-- ==== Generated by WP-Notify Plugin ==== -->
